import { PresetTemplate } from "./types";

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    name: "Social Post (Padrão)",
    description: "Post desmontável semelhante à imagem enviada, pronto para customização",
    category: "Social Media",
    settings: {
      width: 800,
      height: 320,
      backgroundColor: "#f4f0fa", // light purple tint background
      borderRadius: 24,
      boxShadow: "lg"
    },
    elements: [
      {
        id: "main-container",
        type: "container",
        name: "Cartão do Post",
        x: 5,
        y: 10,
        width: 90,
        height: 80,
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 24,
        borderColor: "#f1f1f1",
        borderWidth: 1
      },
      {
        id: "avatar-image",
        type: "avatar",
        name: "Foto de Perfil",
        x: 10,
        y: 20,
        width: 8,
        height: 20,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
        borderRadius: 999,
        borderColor: "#10b981", // green online dot border or badge
        borderWidth: 2
      },
      {
        id: "status-dot",
        type: "badge",
        name: "Indicador Online",
        x: 16.5,
        y: 33,
        width: 1.8,
        height: 4.5,
        rotation: 0,
        opacity: 1,
        zIndex: 6,
        backgroundColor: "#10b981",
        borderRadius: 999
      },
      {
        id: "blue-marker",
        type: "badge",
        name: "Marcador Lateral Azul",
        x: 7.5,
        y: 28,
        width: 1.2,
        height: 4,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        backgroundColor: "#3b82f6",
        borderRadius: 999
      },
      {
        id: "user-display-name",
        type: "text",
        name: "Nome do Usuário",
        x: 20,
        y: 20,
        width: 45,
        height: 6,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "Shifter01",
        fontSize: 18,
        fontWeight: "bold",
        fontFamily: "Space Grotesk",
        fontColor: "#0f172a",
        textAlign: "left"
      },
      {
        id: "user-handle",
        type: "text",
        name: "Username (@handle)",
        x: 32,
        y: 21,
        width: 40,
        height: 5,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "@new_shifter",
        fontSize: 13,
        fontWeight: "normal",
        fontFamily: "Inter",
        fontColor: "#64748b",
        textAlign: "left"
      },
      {
        id: "post-time",
        type: "text",
        name: "Tempo de Postagem",
        x: 78,
        y: 21,
        width: 10,
        height: 5,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "1 min",
        fontSize: 13,
        fontWeight: "normal",
        fontFamily: "Inter",
        fontColor: "#64748b",
        textAlign: "right"
      },
      {
        id: "book-icon",
        type: "icon",
        name: "Ícone Book",
        x: 85,
        y: 20,
        width: 3,
        height: 6,
        rotation: 0,
        opacity: 0.7,
        zIndex: 5,
        iconName: "BookOpen",
        fontColor: "#64748b"
      },
      {
        id: "options-icon",
        type: "icon",
        name: "Ícone Mais Opções",
        x: 90,
        y: 20,
        width: 2,
        height: 6,
        rotation: 0,
        opacity: 0.7,
        zIndex: 5,
        iconName: "MoreVertical",
        fontColor: "#64748b"
      },
      {
        id: "post-title",
        type: "text",
        name: "Título do Post",
        x: 20,
        y: 30,
        width: 70,
        height: 10,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "ppp",
        fontSize: 22,
        fontWeight: "bold",
        fontFamily: "Space Grotesk",
        fontColor: "#1e1b4b", // deep indigo
        textAlign: "left"
      },
      {
        id: "post-body",
        type: "text",
        name: "Corpo do Texto",
        x: 20,
        y: 44,
        width: 70,
        height: 12,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at porttitor sem. Aliquam erat volutpat. Donec non nisl eget eros dictum convallis.",
        fontSize: 14,
        fontWeight: "normal",
        fontFamily: "Inter",
        fontColor: "#475569",
        textAlign: "left"
      },
      {
        id: "heart-icon",
        type: "icon",
        name: "Ícone Coração",
        x: 20,
        y: 72,
        width: 3,
        height: 6,
        rotation: 0,
        opacity: 0.6,
        zIndex: 5,
        iconName: "Heart",
        fontColor: "#64748b"
      },
      {
        id: "heart-count",
        type: "text",
        name: "Contagem de Likes",
        x: 23.5,
        y: 73,
        width: 5,
        height: 5,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "142",
        fontSize: 12,
        fontWeight: "medium",
        fontFamily: "Inter",
        fontColor: "#64748b",
        textAlign: "left"
      },
      {
        id: "message-icon",
        type: "icon",
        name: "Ícone Comentário",
        x: 30,
        y: 72,
        width: 3,
        height: 6,
        rotation: 0,
        opacity: 0.6,
        zIndex: 5,
        iconName: "MessageCircle",
        fontColor: "#64748b"
      },
      {
        id: "message-count",
        type: "text",
        name: "Contagem Comentários",
        x: 33.5,
        y: 73,
        width: 5,
        height: 5,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "28",
        fontSize: 12,
        fontWeight: "medium",
        fontFamily: "Inter",
        fontColor: "#64748b",
        textAlign: "left"
      },
      {
        id: "share-icon",
        type: "icon",
        name: "Ícone Compartilhar",
        x: 48,
        y: 72,
        width: 3,
        height: 6,
        rotation: 0,
        opacity: 0.6,
        zIndex: 5,
        iconName: "Share2",
        fontColor: "#64748b"
      },
      {
        id: "bookmark-icon",
        type: "icon",
        name: "Ícone Bookmark",
        x: 90,
        y: 72,
        width: 3,
        height: 6,
        rotation: 0,
        opacity: 0.6,
        zIndex: 5,
        iconName: "Bookmark",
        fontColor: "#64748b"
      }
    ]
  },
  {
    name: "Mockup de Interface Mobile",
    description: "Template de uma tela de smartphone limpa para desconstrução rápida",
    category: "Mobile UI",
    settings: {
      width: 380,
      height: 680,
      backgroundColor: "#111827", // dark background
      borderRadius: 36,
      boxShadow: "2xl"
    },
    elements: [
      {
        id: "iphone-notch",
        type: "badge",
        name: "Notch Superior",
        x: 30,
        y: 2,
        width: 40,
        height: 3.5,
        rotation: 0,
        opacity: 1,
        zIndex: 10,
        backgroundColor: "#000000",
        borderRadius: 16
      },
      {
        id: "card-main",
        type: "container",
        name: "Card de Destaque",
        x: 8,
        y: 12,
        width: 84,
        height: 38,
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        backgroundColor: "#1f2937",
        borderRadius: 20
      },
      {
        id: "card-image",
        type: "image",
        name: "Imagem do Card",
        x: 12,
        y: 15,
        width: 76,
        height: 18,
        rotation: 0,
        opacity: 1,
        zIndex: 3,
        imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
        borderRadius: 12
      },
      {
        id: "card-title",
        type: "text",
        name: "Título da Campanha",
        x: 14,
        y: 35,
        width: 72,
        height: 6,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        text: "Desperte sua Imaginação",
        fontSize: 16,
        fontWeight: "bold",
        fontFamily: "Space Grotesk",
        fontColor: "#ffffff",
        textAlign: "left"
      },
      {
        id: "card-description",
        type: "text",
        name: "Subtítulo de Apoio",
        x: 14,
        y: 41,
        width: 72,
        height: 6,
        rotation: 0,
        opacity: 1,
        zIndex: 4,
        text: "Toque abaixo para desbloquear novas ferramentas mágicas de design.",
        fontSize: 11,
        fontWeight: "normal",
        fontFamily: "Inter",
        fontColor: "#9ca3af",
        textAlign: "left"
      },
      {
        id: "button-action",
        type: "button",
        name: "Botão de Ação",
        x: 15,
        y: 56,
        width: 70,
        height: 7,
        rotation: 0,
        opacity: 1,
        zIndex: 5,
        text: "Começar Agora",
        fontSize: 13,
        fontWeight: "bold",
        fontFamily: "Space Grotesk",
        fontColor: "#ffffff",
        backgroundColor: "#6366f1", // indigo button
        borderRadius: 12,
        textAlign: "center"
      }
    ]
  }
];
